languageCode = "en"
languageName = "English"
weight = 1
title = "Cloud Architecture"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2025"
  #logo = "img/421-4213680_cloud-logo-cloud-icon-clipart.png"
  #description = "A powerful, lightweight theme for Hugo."
  copyright = "© Copyright { year } Cloud Architecture"

[author]
  name = "Mark D. Hughes"
  image = "img/IMG_8667.JPG"
  headline = "Microsoft Cloud Consultant/Architect | Microsoft Certified Trainer | Microsoft Azure & 365 Certified Expert"
  bio = "Microsoft Cloud Consultant/Architect | Microsoft Certified Trainer | Microsoft Azure & 365 Certified Expert"
  links = [
    { github = "https://github.com/markdavidhughes" },
    { linkedin = "https://linkedin.com/in/markdavidhughes/" },
  ]