# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Docs"
#  pageRef = "docs"
#  weight = 10
#
#[[main]]
#  name = "Shortcodes"
#  pageRef = "docs/shortcodes"
#  weight = 15

#[[main]]
#  name = "Examples"
#  weight = 20

#[[main]]
#  name = "Samples"
#  parent = "Examples"
#  pageRef = "samples"
#  weight = 16

#[[main]]
#  name = "Showcase"
#  parent = "Examples"
#  pageRef = "examples"
#  weight = 30

#[[main]]
#  name = "Recipes"
#  parent = "Examples"
#  pageRef = "guides"
#  weight = 40

#[[main]]
#  name = "Users"
#  pageRef = "users"
#  weight = 90

#[[main]]
#  name = "Merch"
#  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "twitter"
#  pre = "x-twitter"
#  url = "https://twitter.com/burufugu"
#  weight = 200

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  weight = 400
  url = "https://linkedin.com/in/markdavidhughes/"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/markdavidhughes/"
  weight = 300


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
 [[footer]]
   name = "Blog"
   pageRef = "blog"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 30

 [[footer]]
   name = "About"
   pageRef = "about"
   weight = 40